// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Airbnb.Models
{
    [Table("Category")]
    public partial class Category
    {
        public Category()
        {
            Hotels = new HashSet<Hotel>();
        }

        [Key]
        public int CategoryId { get; set; }
        [StringLength(100)]
        public string CategoryName { get; set; }

        [InverseProperty("Category")]
        public virtual ICollection<Hotel> Hotels { get; set; }
    }
}