// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Airbnb.Models
{
    [Table("City")]
    public partial class City
    {
        public City()
        {
            CreditCards = new HashSet<CreditCard>();
            Hotels = new HashSet<Hotel>();
        }

        [Key]
        public int CityId { get; set; }
        [StringLength(50)]
        public string CityName { get; set; }

        [InverseProperty("City")]
        public virtual ICollection<CreditCard> CreditCards { get; set; }
        [InverseProperty("City")]
        public virtual ICollection<Hotel> Hotels { get; set; }
    }
}