// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Airbnb.Models
{
    public partial class Facility
    {
        public Facility()
        {
            Hotels = new HashSet<Hotel>();
        }

        [Key]
        public int FacilityId { get; set; }
        [StringLength(50)]
        public string FacilityType { get; set; }

        [ForeignKey("Facility_Id")]
        [InverseProperty("Facilities")]
        public virtual ICollection<Hotel> Hotels { get; set; }
    }
}