// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Airbnb.Models
{
    [Table("Message")]
    public partial class Message
    {
        [Key]
        public int MessageId { get; set; }
        [Required]
        [StringLength(450)]
        public string UserId { get; set; }
        [Required]
        [StringLength(450)]
        public string HotelmangerId { get; set; }
        [Required]
        [Column("Message")]
        public string Message1 { get; set; }
        public bool? Seen { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime TimeOfSeen { get; set; }

        [ForeignKey("HotelmangerId")]
        [InverseProperty("MessageHotelmangers")]
        public virtual AspNetUser Hotelmanger { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("MessageUsers")]
        public virtual AspNetUser User { get; set; }
    }
}