// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Airbnb.Models
{
    [Table("PaymentType")]
    public partial class PaymentType
    {
        public PaymentType()
        {
            Invoices = new HashSet<Invoice>();
        }

        [Key]
        public int PaymentID { get; set; }
        [Column("PaymentType")]
        [StringLength(100)]
        public string PaymentType1 { get; set; }

        [InverseProperty("PaymentType")]
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}