// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Airbnb.Models
{
    public partial class Review
    {
        [Key]
        public int ReviewId { get; set; }
        [Column("Review")]
        [StringLength(255)]
        public string Review1 { get; set; }
        public int? Hotel_Id { get; set; }
        [StringLength(450)]
        public string User_Id { get; set; }

        [ForeignKey("Hotel_Id")]
        [InverseProperty("Reviews")]
        public virtual Hotel Hotel { get; set; }
        [ForeignKey("User_Id")]
        [InverseProperty("Reviews")]
        public virtual AspNetUser User { get; set; }
    }
}