// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Airbnb.Models
{
    [Table("Room")]
    public partial class Room
    {
        public Room()
        {
            Bookings = new HashSet<Booking>();
        }

        [Key]
        public int RoomId { get; set; }
        public string Description { get; set; }
        public bool? Is_Available { get; set; }
        public int? Hotel_Id { get; set; }
        [StringLength(100)]
        public string RoomType { get; set; }
        [Column(TypeName = "money")]
        public decimal? Price { get; set; }

        [ForeignKey("Hotel_Id")]
        [InverseProperty("Rooms")]
        public virtual Hotel Hotel { get; set; }

        [ForeignKey("Room_Id")]
        [InverseProperty("Rooms")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}