// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Airbnb.Models
{
    [Table("Transaction")]
    public partial class Transaction
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Amount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        public int? BookingId { get; set; }

        [ForeignKey("BookingId")]
        [InverseProperty("Transactions")]
        public virtual Booking Booking { get; set; }
    }
}